In [1]:
%load_ext autoreload

In [1]:
%reload_ext autoreload
import gymnasium as gym
import numpy as np
import math
import torch
from torch import nn
import torch.nn.functional as F
from ICM import *
from mainNetwork import *
from worker import *

In [2]:
env = gym.make("BipedalWalker-v3", hardcore=True)

In [3]:
icm1 = ICM(env.observation_space.shape[0],env.action_space.shape[0])

In [6]:
wrkr = worker(env)

In [7]:
memoryBig = wrkr.storeMemory()

[[array([ 2.7463958e-03,  7.0931046e-06, -9.2493510e-04, -1.6000047e-02,
          9.2378214e-02,  2.1471947e-03,  8.5991037e-01, -3.0427752e-04,
          1.0000000e+00,  3.2723341e-02,  2.1470892e-03,  8.5359186e-01,
         -1.4609619e-03,  1.0000000e+00,  4.4081357e-01,  4.4581968e-01,
          4.6142232e-01,  4.8954970e-01,  5.3410226e-01,  6.0246044e-01,
          7.0914817e-01,  8.8593090e-01,  1.0000000e+00,  1.0000000e+00],
        dtype=float32),
  array([0.07758165, 0.36940107, 0.00078563, 0.24074379], dtype=float32),
  array([ 0.00762615,  0.00230037,  0.01304194,  0.02154987, -0.2741261 ,
         -0.78199834,  1.4466758 ,  0.99518985,  1.        ,  0.26687035,
         -0.5243081 ,  0.22230858,  0.65785366,  1.        ,  0.45587587,
          0.46105304,  0.4771888 ,  0.50627726,  0.5523522 ,  0.6230461 ,
          0.7333793 ,  0.9162026 ,  1.        ,  1.        ], dtype=float32),
  array([ 0.03363983,  0.10345876,  0.00107582, -0.09255265,  0.0435727 ,
          0.005

In [8]:
memoryBig[0]

[array([ 2.7463958e-03,  7.0931046e-06, -9.2493510e-04, -1.6000047e-02,
         9.2378214e-02,  2.1471947e-03,  8.5991037e-01, -3.0427752e-04,
         1.0000000e+00,  3.2723341e-02,  2.1470892e-03,  8.5359186e-01,
        -1.4609619e-03,  1.0000000e+00,  4.4081357e-01,  4.4581968e-01,
         4.6142232e-01,  4.8954970e-01,  5.3410226e-01,  6.0246044e-01,
         7.0914817e-01,  8.8593090e-01,  1.0000000e+00,  1.0000000e+00],
       dtype=float32),
 array([0.07758165, 0.36940107, 0.00078563, 0.24074379], dtype=float32),
 array([ 0.00762615,  0.00230037,  0.01304194,  0.02154987, -0.2741261 ,
        -0.78199834,  1.4466758 ,  0.99518985,  1.        ,  0.26687035,
        -0.5243081 ,  0.22230858,  0.65785366,  1.        ,  0.45587587,
         0.46105304,  0.4771888 ,  0.50627726,  0.5523522 ,  0.6230461 ,
         0.7333793 ,  0.9162026 ,  1.        ,  1.        ], dtype=float32),
 array([ 0.03363983,  0.10345876,  0.00107582, -0.09255265,  0.0435727 ,
         0.00518802,  0.04728

In [25]:
# ICM working, not optimized
env.reset()
i = 0
while True:

    curr, _, _, _, _ = env.step(env.action_space.sample())
    action  = env.action_space.sample()
    next, reward, _, _, _  = env.step(action)
    pred_nextState = icm1.forwardModel(curr, action)
    loss, intrinsicReward = icm1.forwardLossAndReward(next)
    
    if reward == -100:
        print(reward)
        print(i)
        break
    i += 1

print(curr.shape)
print(action)
print(next.shape)
print(pred_nextState.shape)
print(loss)

KeyboardInterrupt: 

In [29]:
worker1 = mainLoop(env.observation_space.shape[0],env.action_space.shape[0])

In [36]:
print(env.observation_space.sample())
curr = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
print(curr)
[-3.14 -5. -5. -5. -3.14 -5. -3.14 -5. -0. -3.14 -5. -3.14 -5. -0. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. ]

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1417661251.py, line 2)

In [56]:
# mainLoop test successful
curr1 = env.reset()
curr, _, _, _, _ = env.step(env.action_space.sample())
print(worker1.forwardPass(curr1[0]))


[ 0.03028351  0.00777736  0.04459332 -0.0023227 ]


In [52]:
# # env.reset()
# # for i in range(1000):
# #     env.render()
# #     action = env.action_space.sample()
# #     env.step(action)

# env??

In [5]:
# env.close()